analysis:
  RMSD:
    backbone_rmsd:
      title: 'Backbone RMSD'
      selection: 'protein and name CA'
      fit_selection: 'protein and name CA'
  RMSF:
    backbone_rmsf:
      title: 'Backbone RMSF'
      selection: 'protein and name CA'
      fit_selection: 'protein and name CA'
dt_per_frame: 40         

compute_features:
  plumed_settings:
    traj_stride: 1
    moltype: protein
    input_name: combined_features
    whole_molecule_selection: all
    features:
      distance_groups:
        ca_dist:
          first_selection: "name CA"
          second_selection: "name CA"
          first_stride: 3
          second_stride: 5
          skip_neigh_residues: True
          skip_bonded_atoms: True
      dihedral_groups:         
        ca_tors:             
          selection: "name CA"          
          periodic_encoding: True   
          search_mode: virtual 

filter_features:       
  filter_settings:
    compute_diptest: False # Do not filter, use all features            
    compute_entropy: False             
    compute_std: False                
    diptest_significance_level: 0.5
    entropy_quantile: 0                
    std_quantile: 0                                                    

train_colvars:
  cvs: ['vae']
  common:
    dimension: 2
    lag_time: 1 
    architecture:
      encoder: 
        layers: [32, 16, 8]
        dropout: 0.1
      decoder: 
        layers: [4, 8]
        dropout: 0.1
    training: 
      general:
        max_tries: 1
        seed: 42
        lengths: [0.8, 0.2]
        batch_size: 128
        max_epochs: 8000
        shuffle: True
        random_split: True
        check_val_every_n_epoch: 1
        save_check_every_n_epoch: 1
      early_stopping:
        patience: 8000
        min_delta: 1.0e-04
      optimizer:
        name: Adam
        kwargs: 
          lr: 1.0e-03
          weight_decay: 0
      kl_annealing:
        type: linear
        start_beta: 0
        max_beta: 0.01
        start_epoch: 3000
        n_epochs_anneal: 2000
      save_loss: True
      plot_loss: True
    bias:
      method: opes_metad_explore
  figures:
    fes:
      compute: True  
      save: True  
      temperature: 300
      bandwidth: 0.025
      num_bins: 200
      max_fes: 30
    traj_projection:
      plot: True
      num_bins: 100
      bandwidth: 0.25
      alpha: 0.6
      cmap: turbo
      marker_size: 12
  clustering:                        
    run: False                        
    algorithm: hdbscan               
    opt_num_clusters: True          
    search_interval: [3, 8]          
    num_clusters: 3                  
    linkage: complete                
    n_init: 20                       
    min_cluster_size: 50             
    min_samples: 5                  
    cluster_selection_epsilon: 0
