compute_features:
  plumed_settings:
    traj_stride: 1
    features:
      distance_groups:
        dist:
          first_selection: "all"
          second_selection: "all"
          first_stride: 5
          second_stride: 15
          skip_neigh_residues: False
          skip_bonded_atoms: True

filter_features:       
  filter_settings:
    compute_diptest: True              
    compute_entropy: False             
    compute_std: False                
    diptest_significance_level: 0.05   
    entropy_quantile: 0                
    std_quantile: 0                                                      

train_colvars:
  cvs: ['pca', 'deep_tica', 'tica', 'ae']
  common:
    dimension: 2
    lag_time: 1 
    features_normalization: 'mean_std'
    architecture:
      encoder:
        layers: [5, 3]
    training: 
      general:
        max_tries: 1
        seed: 42
        lengths: [0.8, 0.2]
        batch_size: 128
        max_epochs: 10000
        dropout: 0.1
        shuffle: False
        random_split: True
        check_val_every_n_epoch: 1
        save_check_every_n_epoch: 1
      early_stopping:
        patience: 100
        min_delta: 1.0e-05
      optimizer:
        name: Adam
        kwargs: 
          lr: 1.0e-03
          weight_decay: 0
      save_loss: True
      plot_loss: True

traj_projection:  
  figures:
    fes:
      compute: True  
      save: True  
      temperature: 300
      bandwidth: 0.015
      num_fes_levels: 20
      num_bins: 250
      max_fes: 30
    traj_projection:
      alpha: 1
      bandwidth: 0.25
      cmap: turbo
      marker_size: 5
      num_bins: 100
      plot: true

traj_cluster:                      
  run: False
