compute_features:
  plumed_settings:
    traj_stride: 1
    features:
      distance_groups:
        dist:
          first_selection: "name O and resid 1"
          second_selection: "(name CH3 and resid 3) or (name CB and resid 2)"
          first_stride: 1
          second_stride: 1
          skip_neigh_residues: False
          skip_bonded_atoms: True

filter_features:       
  filter_settings:
    compute_diptest: True              
    compute_entropy: False             
    compute_std: False                                                                     

train_colvars:
  cvs: ['pca', 'ae', 'vae', 'tica', 'deep_tica']
  common:
    dimension: 1
    lag_time: 1
    features_normalization: 'mean_std'
    architecture:
      encoder: 
        layers: [4, 20, 20, 2]
        dropout: [null, null, null, null]
        activation: [leaky_relu, leaky_relu, leaky_relu, leaky_relu]
        batchnorm: False
      decoder: 
        layers: [2, 20, 20, 4]
        dropout: [null, null, null, null]
        activation: [leaky_relu, leaky_relu, leaky_relu, leaky_relu]
        batchnorm: False
    training: 
      general:
        max_tries: 1
        seed: 42
        lengths: [0.8, 0.2]
        batch_size: 128
        max_epochs: 2000     # 200
        shuffle: True
        random_split: True
        check_val_every_n_epoch: 1
        save_check_every_n_epoch: 1
      early_stopping:
        patience: 2000 # 200
        min_delta: 1.0e-05
      optimizer:
        name: Adam
        kwargs: 
          lr: 1.0e-04  #  1.0e-03
          weight_decay: 0.0
      save_loss: True
      plot_loss: True
  figures:
    fes:
      compute: False  
      save: False  
      temperature: 300
      bandwidth: 0.025
      num_bins: 200
      num_blocks: 1
      max_fes: 18
    traj_projection:
      plot: True
      num_bins: 100
      bandwidth: 0.25
      alpha: 0.6
      cmap: turbo
      marker_size: 12

clustering:                        
  run: False                        
